jsStr = {
	common_defaultcurrencyformatpattern               : '#,##0,00',
	common_dateformat                                 : 'dd-MM-yyyy',
	common_integerformatpattern                       : '#,##0',
	common_percentage                                 : '{0}%',
	lblclose                                          : 'Sluiten',
	lblno                                             : 'Nee',
	lblok                                             : 'OK',
	lblyes                                            : 'Ja',
	rfamessagecode_country_required                   : 'Land/regio is verplicht.',
	rfamessagecode_exists_on_job                      : 'Er is al een gebruiker met dit e-mailadres toegevoegd aan deze baan.',
	rfamessagecode_ownership_by_duration_cannot_refer : 'Een medewerker heeft deze persoon al aanbevolen voor de vacature. U kunt de persoon pas aanbevelen voor een vacature als de andere verwijzing via een medewerker inactief wordt.',
	rfamessagecode_email_invalid                      : 'Het opgegeven e-mailadres is ongeldig.',
	rfamessagecode_phone_invalid                      : 'Het opgegeven telefoonnummer is ongeldig.',
	rfamessagecode_employee_does_not_have_permissions : 'U bent niet gemachtigd om deze verwijzing te verzenden.',
	rfamessagecode_employee_referral_not_enabled      : 'Verwijzing is niet ingeschakeld voor dit bedrijf.',
	rfamessagecode_first_name_required                : 'Voornaam is verplicht.',
	rfamessagecode_invalid_resume_type                : 'De cv is niet van een geldig type. Upload een andere type.',
	rfamessagecode_exceeded_file_size                 : 'Het bijgevoegde bestand heeft de maximale grootte overschreden. Voeg een andere bestand bij.',
	rfamessagecode_job_req_id_not_valid               : 'Er is een probleem met deze baan, probeer een andere baan.',
	rfamessagecode_last_name_required                 : 'Achternaam is verplicht.',
	rfamessagecode_phone_number_required              : 'Telefoonnummer is verplicht.',
	rfamessagecode_primary_email_required             : 'Primair e-mailadres is verplicht.',
	rfamessagecode_resume_required                    : 'Een cv is verplicht.',
	rfamessagecode_success                            : 'Uw verwijzing is ingediend.',
	rfamessagecode_unknown                            : 'Er is een fout opgetreden tijdens het indienen van uw verwijzing. Probeer het later opnieuw.',
	searchpagetitlenokeyword                          : '{0}: vacatures',
	ssopasswordisinvalid                              : 'Het wachtwoord is ongeldig. Voer het wachtwoord in dat u net hebt gereset.',
	ssopasswordfailed                                 : 'Wij kunnen uw accounts helaas niet synchroniseren.',
	tcagentalreadyexists                              : 'U heeft al een waarschuwing die overeenkomt met deze criteria.',
	tcagentscouldnotbesaved                           : 'Uw waarschuwingen konden niet worden opgeslagen. Probeer het a.u.b. opnieuw.',
	tcalreadyamember                                  : 'Al lid?',
	tcalreadyauserofthissite                          : 'U bent al gebruiker van deze website.\n\nLog a.u.b. in voor het beheren van uw profiel en waarschuwingen.',
	tccheckinput                                      : 'Controleer a.u.b. uw invoer.',
	tcconfirminvalid                                  : 'Bevestigen dat wachtwoord ongeldig is.',
	tcconfirmisinvalid                                : '{0} is ongeldig.',
	tcconfirmrequired                                 : 'Bevestigen dat wachtwoord verplicht is.',
	tccookiesmustbeenabled                            : 'Cookies moeten toegestaan zijn om verder te kunnen gaan.',
	tcday                                             : 'dag',
	tcdays                                            : 'dagen',
	tcdeletetheseagents                               : 'Weet u zeker dat u deze waarschuwingen wilt verwijderen?',
	tcdeletethisagent                                 : 'Weet u zeker dat u deze waarschuwing wilt verwijderen?',
	tcemailaddressrequired                            : 'E-mailadres is vereist.',
	tcemailnotvalid                                   : 'Het e-mailadres is geen geldig e-mailadres.',
	tcemailrequired                                   : 'E-mailadres is verplicht.',
	tcfinishingsubscribe                              : 'Inschrijving afmaken',
	tcfreqmustbegtone                                 : 'Frequentie moet minstens 1 zijn.',
	tcfreqmustbenumeric                               : 'Frequentie moet een cijfer zijn.',
	tcgivenyouapassword                               : 'Wij hebben u een wachtwoord gegeven.',
	tcgivenyouapasswordhelp                           : 'Wij hebben al een wachtwoord voor u aangemaakt.\n\nDoor te klikken op "Persoonlijk maken?" kunt u het wachtwoord vervangen\ndoor een ander wachtwoord.',
	tchelp                                            : 'Help',
	tcjobresultsa11yaccordionchecklabel               : '{0}, {1} resultaten, {2} van {3} posities',
	tcjobresultsa11yaccordionsinglechecklabel         : '{0}, 1 resultaat, {1} van {2} posities',
	tcjobresultsa11yfiltersearchlabel                 : '{0} zoeken',
	tcjobresultsa11yiframetitle                       : 'Google Job Map',
	tcjobresultsa11yjoblistitem                       : '{0}, {1} van {2}',
	tcjobresultsa11ypagegoto                          : 'Naar pagina {0} gaan',
	tcjobresultsa11ypagenextlabel                     : 'Naar volgende pagina',
	tcjobresultsa11ypagepreviouslabel                 : 'Naar vorige pagina',
	tcjobresultsa11ypageregionlabel                   : 'Paginering',
	tcjobresultsa11ytokenlabel                        : '{0} verwijderen',
	tcjobresultsbacktoresults                         : 'Terug naar resultaten',
	tcjobresultsclear                                 : 'Alles wissen',
	tcjobresultscreatejobalertscategorytext           : 'Vacaturewaarschuwingen voor deze categorie ontvangen',
	tcjobresultscreatejobalertsdetailstext            : 'Link vacaturewaarschuwingen',
	tcjobresultscreatejobalerttext                    : 'Vacaturewaarschuwingen voor deze zoekpdracht ontvangen',
	tcjobresultsdropdownrecent                        : 'Meest recent',
	tcjobresultsdropdownrelevant                      : 'Meest relevant',
	tcjobresultserrmaptitle                           : 'Uw zoekresultaten kunnen niet worden weergegeven op de kaart.',
	tcjobresultserrmapsubtitle                        : 'Bekijk in plaats daarvan uw resultaten in de lijstview.',
	tcjobresultsfilterheader                          : 'Uw zoekopdracht verfijnen',
	tcjobresultsfilterlimitdescription                : 'U kunt maximaal {0} filters selecteren. Hef de selectie van enkele filters op om nieuwe te selecteren.',
	tcjobresultsfilterlimittitle                      : 'Filterlimiet bereikt',
	tcjobresultsfiltersearchplaceholder               : 'Zoeken',
	tcjobresultsheadersortby                          : 'Sorteren op',
	tcjobresultsheadertitle                           : '{0} tot {1} van {2} resultaten',
	tcjobresultssingularheadertitle                   : '1 van 1 resultaat',
	tcjobresultsmoretokes                             : 'Nog {0}',
	tcjobresultsmobileheadersingular                  : '1 vacature',
	tcjobresultsmapheader                             : '{0} vacatures gevonden',
	tcjobresultsmapsingularheader                     : '1 vacature gevonden',
	tcjobresultsmultiplelocations                     : 'Meerdere locaties',
	tcjobresultsnocoordinates                         : 'Er zijn geen vacatures die aan uw criteria voldoen. Gebruik andere zoektermen of wijzig uw filterselecties.',
	tcjobresultsnofilterdata                          : 'Geen informatie beschikbaar',
	tcjobresultsnojobsfound                           : 'Geen vacatures gevonden',
	tcjobresultspagenext                              : 'Volgende',
	tcjobresultspageprevious                          : 'Vorige',
	tcjobresultsrefine                                : 'Verfijnen',
	tcjobresultssearchresults                         : 'Zoekresultaten',
	tcjobresultsshowless                              : 'Minder weergeven',
	tcjobresultssortbyrecent                          : 'Sorteren op meest recente',
	tcjobresultssortbyrelevant                        : 'Sorteren op meest relevante',
	tcjobresultsswitchtitle                           : 'Schakelen tussen lijst- en kaartweergave',
	tcjobresultsswitchmap                             : 'Kaartweergave',
	tcjobresultsswitchlist                            : 'Lijstweergave',
	tcsocialescape                                    : 'Als er een probleem optreedt tijdens het gebruik van verificatie van {0} of als u verificatie van {0} wilt gebruiken, {linkOpen}vult u het formulier zelf in{linkClose}.',
	tcsocialwaiting                                   : 'Wachten op {0}',
	tclockedout                                       : 'U hebt het toegestane aantal mislukte aanmeldingspogingen overschreden en uw account is vergrendeld. Klik op "Wachtwoord vergeten?" om uw wachtwoord opnieuw in te stellen en uw account te ontgrendelen.',
	tcloginfailed                                     : 'Uw poging tot aanmelden is mislukt. Controleer of uw e-mailadres en wachtwoord correct zijn ingevoerd.',
	tcmhomepage                                       : 'homepage',
	tcminvalidemailmessage                            : 'Voer een geldig e-mailadres in.',
	tcmjobpage                                        : 'banenpagina',
	tcmloggedin                                       : 'U bent aangemeld als',
	tcmloginfailed                                    : 'Als u uw wachtwoord vergeten bent, klik dan op de onderstaande link van de niet-mobiele versie en klik dan op Wachtwoord vergeten?',
	tcmpleasesignin                                   : 'Meld u aan voor toegang tot uw profiel.',
	tcmsave                                           : 'Sla op',
	tcmustprovidekeywordorloc                         : 'U moet een trefwoord of een plaats invullen, of beide.',
	tcnotvalidemail                                   : '{0} is geen geldig e-mailadres.',
	tcnotvalidurl                                     : '{0} is geen geldige {1} URL.',
	tcpasswordconfirmmustmatch                        : 'Wachtwoord en bevestiging van wachtwoord moeten overeenkomen.',
	tcpasswordrequired                                : 'Wachtwoord is verplicht.',
	tcpasswordtoolong                                 : 'Uw wachtwoord is te lang.',
	tcpasswordtooweak                                 : 'Wachtwoord is te zwak.',
	tcpasswordvalid                                   : 'Wachtwoord is geldig.',
	tcpasswordvalidmatches                            : 'Wachtwoord is geldig en komt overeen.',
	tcpasswordsdonotmatch                             : 'Wachtwoorden komen niet overeen.',
	tcpersonalizeit                                   : 'Persoonlijk maken?',
	tcpleasecheckyourinput                            : 'Controleer a.u.b. uw invoer.',
	tcpleasewait                                      : 'Wacht even alstublieft...',
	tcprivacypolicyoutofdate                          : 'Bekijk de meest recente versie van de privacyakkoordverklaring.',
	tcprofilecantbesaved                              : 'Uw profiel kon niet opgeslagen worden. Probeer het a.u.b. opnieuw.',
	tcprofileinvalidagent                             : 'Uw waarschuwing is ongeldig en wordt niet opgeslagen.',
	tcpwconfirmmatch                                  : 'Wachtwoord en bevestiging moeten overeenkomen.',
	tcpwhasbeenreset                                  : 'Als een account overeenkomt met het door u ingevoerde e-mailadres, ontvangt u een e-mail met instructies over de manier waarop u uw wachtwoord kunt herstellen. Elke keer dat u uw wachtwoord herstelt, worden alle vorige wachtwoordherstellinks in e-mails geblokkeerd.',
	tcpwrequirements                                  : 'Wachtwoorden moeten overeenkomen, {0}-20 tekens lang zijn en bestaan uit:\n   - ten minste één letter\n   - ten minste één cijfer of speciaal teken\n   - niet meer dan drie dezelfde tekens achter elkaar',
	tcpwresetsuccess                                  : 'Uw wachtwoord is met succes hersteld.',
	tcredirectingtojob                                : 'Bezig met omleiden naar baan',
	tcremembermehelp                                  : 'Bij het kiezen van "Onthoud mij" wordt er een permanente cookie aangemaakt op uw computer; deze optie mag daarom niet worden gebruikt op openbare of gezamenlijke computers.',
	tcresetpasswordemail                              : 'Voer hierboven een geldig e-mailadres in.',
	tcreviewprivacypolicy                             : 'De privacyakkoordverklaring moet worden gecontroleerd.',
	tcsavingagents                                    : 'Waarschuwingen opslaan',
	tcsavingprofile                                   : 'Opslaan profiel',
	tcsorry                                           : 'Sorry!',
	tcsorrygenericerror                               : 'Sorry, er is een fout opgetreden. Probeer het a.u.b. opnieuw.',
	tcsuccess                                         : 'Succes!',
	tctoskipenablecookies                             : 'Controleer of cookies toegestaan zijn, om deze stap in het vervolg over te slaan.',
	tcusernotinsystem                                 : 'De gebruiker bestaat niet in ons systeem.',
	tcvalidateisrequired                              : 'Het veld {0} is verplicht.',
	tcyoudonthaveagents                               : 'U heeft geen enkele waarschuwingen.',
	tcyouhavemaxagentsallowed                         : 'U hebt al het maximaal toegestane aantal waarschuwingen.',
	pageexpiredmessage                                : 'Het spijt ons. De pagina die u probeert te openen is verlopen.',
	tcnumberofresultsmultiplepages                    : '{0} van {1} vacatures gevonden',
	tcnumberofresultssinglepage                       : '{0} vacatures gevonden',
	tcnojobsfoundforsearch                            : 'We hebben geen vacatures gevonden die overeenkomen.',
	tcnojobsfoundforsearchsubtitle                    : 'Controleer uw spelling of overweeg een andere term te gebruiken en probeer het opnieuw.',
	tcerrorinprocessingsearch                         : 'We kunnen uw zoekopdracht op dit moment niet verwerken.',
	tconejobfound                                     : '1 vacature gevonden',
	tlpnoresultsattention                             : 'Er zijn momenteel geen passende vacatures in deze categorie of plaats.'
};